### ISSUE TITLE
Можно сократить

### ISSUE THREAD

**Issue by yhaskell** [vki-group-503b/bayrakh#1]
https://github.com/vki-group-503b/bayrakh/blob/15c9b3b33a524cb0b2bb50ceb4a22a7c394103cd/src/ru/nsu/hci/bayrakh/javalabs/lab3/Calculator.java#L8-L24

Можно сократить:
```java
  c >= '0' && c <= '9'
```

https://github.com/vki-group-503b/bayrakh/blob/15c9b3b33a524cb0b2bb50ceb4a22a7c394103cd/src/ru/nsu/hci/bayrakh/javalabs/lab3/Calculator.java#L25-L39

```java
c - '0'
```

**Comment by kaktus30898** [comment]
Исправила
